spring.datasource.url: jdbc:mysql://localhost:3306/chat1?useSSL=false
  &serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: testtest
#spring.jpa.hibernate.ddl-auto: update
spring.jpa.hibernate.ddl-auto: create-drop